#!/bin/bash

if [ -z "$1" ]; then
    rm -rf build
    cmake -S . -B build -G "Unix Makefiles"
elif [[ "$1" == "b" ]]; then
    cmake --build build -j 12
elif [[ "$1" == "r" ]]; then
    ./build/sim-bpred -redir:sim applu_simout.res  -redir:prog applu_progout.res -max:inst 500000000 -nice 1 -bpred oghel ./inputs/ss_files/applu.ss < ./inputs/in_files/applu.in
fi
